export const API = {
  auth: {
    login: '/auth/login/',
    register: '/auth/register/',
    registerInvite: '/auth/register/invite/',
    logout: '/auth/logout/',
    me: '/auth/me/',
    refreshToken: '/auth/token/refresh/',
    forgotPassword: '/auth/password/reset/',
    resetPassword: '/auth/password/reset/confirm/',
    changePassword: '/auth/me/password/',
    updateMe: '/auth/me/update/',
    deleteAvatar: '/auth/me/avatar/',
    verifyEmail: '/auth/email/verify/',
    resendVerification: '/auth/email/resend/',
    roles: '/auth/roles/',
  },
  admin: {
    users: '/auth/users/',
    userDetail: (id: number) => `/auth/users/${id}/`,
    userBlock: (id: number) => `/auth/users/${id}/block/`,
    userUnblock: (id: number) => `/auth/users/${id}/unblock/`,
  },
  activity: {
    feed: '/auth/me/activity/',
  },
  core: {
    ping: '/ping/',
    health: '/health/',
    dashboard: '/dashboard/',
    calendarEvents: '/calendar/events/',
  },
  bookings: {
    resources: '/bookings/resources/',
    resource: (id: number) => `/bookings/resources/${id}/`,
    resourceSchedule: (id: number) => `/bookings/resources/${id}/schedule/`,
    reservations: '/bookings/reservations/',
    myReservations: '/bookings/reservations/my/',
    reservation: (id: number) => `/bookings/reservations/${id}/`,
    cancelReservation: (id: number) => `/bookings/reservations/${id}/cancel/`,
    adminCancelReservation: (id: number) => `/bookings/reservations/${id}/admin-cancel/`,
    bulkCancelReservations: '/bookings/reservations/bulk-cancel/',
    checkIn: (id: number) => `/bookings/reservations/${id}/check-in/`,
    participants: (id: number) => `/bookings/reservations/${id}/participants/`,
    removeParticipant: (id: number, userId: number) =>
      `/bookings/reservations/${id}/participants/${userId}/`,
    qrImage: (qrCode: string) => `/bookings/reservations/qr/${qrCode}/image/`,
    validateQr: '/bookings/reservations/validate-qr/',
    members: '/bookings/members/',
    recurring: '/bookings/recurring/',
    recurringDetail: (id: number) => `/bookings/recurring/${id}/`,
  },
} as const;
